# **Num**erical**Py**thon

* NumPy is wirtten in C, which is way faster than Python. 
* It's avoiding loops using vectorization. 
* It's the backbone of other Python scientific packages

In [1]:
import numpy as np

## 1. DataTypes & Attributes
**ndarray**

In [2]:
# NumPy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2, 3.3], 
               [4, 5, 6.5]])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [5]:
a3 = np.array([[[1, 2, 3], 
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]],
               [[19, 20, 21],
                [22, 23, 24],
                [25, 26, 27]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [6]:
a1.shape, a2.shape, a3.shape

((3,), (2, 3), (3, 3, 3))

In [7]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [8]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [9]:
a1.size, a2.size, a3.size

(3, 6, 27)

In [10]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [11]:
# Create a DataFrame from NumPy array
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating arrays

In [12]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [13]:
sample_array.dtype

dtype('int64')

In [14]:
ones = np.ones(shape=(2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
ones.dtype

dtype('float64')

In [16]:
type(ones)

numpy.ndarray

In [17]:
zeros = np.zeros((3, 3, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [18]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [19]:
random_array = np.random.randint(low=0, high=10, size=(3, 5))
random_array

array([[0, 3, 1, 9, 6],
       [6, 9, 5, 9, 2],
       [8, 9, 0, 9, 8]])

In [20]:
random_array.size, random_array.shape

(15, (3, 5))

In [21]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.41468418, 0.24735268, 0.32734008],
       [0.58170022, 0.89980846, 0.87407562],
       [0.89524513, 0.92733055, 0.63816496],
       [0.38320538, 0.11793869, 0.95624079],
       [0.37593554, 0.51743107, 0.07972136]])

In [22]:
random_array_2.shape

(5, 3)

In [26]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.95561188, 0.717322  , 0.70959132],
       [0.22718477, 0.31865325, 0.47025919],
       [0.58499686, 0.54476886, 0.82376033],
       [0.32489848, 0.69503287, 0.49317138],
       [0.1223942 , 0.89399765, 0.4920606 ]])

In [55]:
# Pseudo-random numbers
np.random.seed(99999)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

In [48]:
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [49]:
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992],
       [0.90912837, 0.13316945, 0.52341258],
       [0.75040986, 0.66901324, 0.46775286]])

## 3. Viewing Arrays and Matrices

In [56]:
np.unique(random_array_4)

array([0, 1, 3, 4, 5, 6, 8, 9])

In [57]:
a1

array([1, 2, 3])

In [58]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [59]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [60]:
a1[0]

1

In [61]:
a2[0]

array([1. , 2. , 3.3])

In [62]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
a2[1]

array([4. , 5. , 6.5])

In [59]:
a3[:3, :2, :1]

array([[[ 1],
        [ 4]],

       [[10],
        [13]],

       [[19],
        [22]]])

In [60]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[2, 5, 8, 5, 3],
         [2, 2, 7, 8, 7],
         [3, 9, 1, 2, 0],
         [3, 3, 1, 1, 7]],

        [[7, 2, 2, 2, 0],
         [7, 3, 4, 9, 5],
         [2, 2, 4, 1, 9],
         [1, 1, 2, 3, 2]],

        [[0, 7, 7, 7, 8],
         [3, 9, 3, 6, 3],
         [5, 9, 0, 8, 6],
         [2, 7, 5, 1, 3]]],


       [[[7, 0, 0, 5, 4],
         [3, 1, 8, 1, 6],
         [3, 2, 8, 9, 9],
         [1, 4, 1, 1, 1]],

        [[9, 6, 4, 8, 9],
         [2, 5, 1, 5, 7],
         [8, 9, 5, 4, 7],
         [2, 6, 1, 1, 3]],

        [[3, 3, 8, 6, 0],
         [2, 2, 4, 4, 0],
         [9, 5, 9, 5, 1],
         [4, 1, 6, 8, 9]]]])

In [62]:
# Get the first 4 numbers of the inner most arrays
a4[:, :, :, :2]

array([[[[2, 5],
         [2, 2],
         [3, 9],
         [3, 3]],

        [[7, 2],
         [7, 3],
         [2, 2],
         [1, 1]],

        [[0, 7],
         [3, 9],
         [5, 9],
         [2, 7]]],


       [[[7, 0],
         [3, 1],
         [3, 2],
         [1, 4]],

        [[9, 6],
         [2, 5],
         [8, 9],
         [2, 6]],

        [[3, 3],
         [2, 2],
         [9, 5],
         [4, 1]]]])

## 4. Manipulating & comparing arrays

### Arithmetic

In [64]:
a1

array([1, 2, 3])

In [65]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [66]:
a1 + ones

array([[2., 3., 4.],
       [2., 3., 4.]])

In [67]:
a1 - ones

array([[0., 1., 2.],
       [0., 1., 2.]])

In [68]:
a1 * ones

array([[1., 2., 3.],
       [1., 2., 3.]])

In [69]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [70]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [71]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [73]:
# How can you reshape a2 to be compatible with a3?
# Search: How to research numpy array?
a2 * a3

ValueError: ignored

In [77]:
a1

array([1, 2, 3])

In [74]:
a1 / ones

array([[1., 2., 3.],
       [1., 2., 3.]])

In [75]:
a2 / a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [76]:
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [78]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [79]:
np.add(a1, ones)

array([[2., 3., 4.],
       [2., 3., 4.]])

In [80]:
a1 % 2

array([1, 0, 1])

In [83]:
np.mod(a1, 2)

array([1, 0, 1])

In [85]:
a2 % 2

array([[1. , 0. , 1.3],
       [0. , 1. , 0.5]])

In [86]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [87]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

### Aggregation

Aggregation = performing the same operation on a number of things.

In [89]:
listy_list = [1, 2, 3]
type(listy_list)

list

In [90]:
sum(listy_list)

6

In [91]:
a1

array([1, 2, 3])

In [93]:
type(a1)

numpy.ndarray

In [94]:
sum(a1)

6

In [95]:
np.sum(a1)

6

# Use Python's methods (`sum()`) on Python datatypes and use NumPy's methods (`np.sum()`) on Numpy arrays

In [100]:
# Creative a massive NumPy array
massive_array = np.random.random(100_000)
massive_array[:10]

array([0.88852404, 0.8782151 , 0.91424035, 0.61780797, 0.12991654,
       0.85451302, 0.13656007, 0.72837252, 0.96554463, 0.56975408])

In [101]:
%timeit sum(massive_array) # Python's sum()
%timeit np.sum(massive_array) # NumPy's sum()

100 loops, best of 5: 8.47 ms per loop
The slowest run took 18.01 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 5: 38.9 µs per loop


In [102]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [103]:
np.mean(a2)

3.6333333333333333

In [105]:
np.min(a2), np.max(a2), np.std(a2), np.var(a2)

(1.0, 6.5, 1.8226964152656422, 3.3222222222222224)

In [106]:
np.sqrt(np.var(a2))

1.8226964152656422